### ISSUE TITLE
[BUG] Taken to channel not video

### ISSUE THREAD

**Issue by KendallDoesCoding** [willnode/random-youtube#1]
This took me to the YT channel, not to the video on my second spin, on my first spin it worked great.:

https://www.youtube.com/channel/UCu7P0oWq0-Y_a1Q-yBb8GXw

**Comment by willnode** [comment]
Thanks for mentioning this issue. I was wondering about this a few days ago, I just remember today that in Google search we have "Video" tab to search only videos. 

I incorporated this into the algorithm. The fix [has landed](https://github.com/willnode/random-youtube/commit/d4d6bedaac94a74ca3395d8c8a3e611432905bef)! It should open videos 100% from now on.

**Comment by willnode** [comment]
Oops, (was) not strong enough. [This change](https://github.com/willnode/random-youtube/commit/441e8eef9eeaf0eb1aaf48fa8a203964871b015c) should be it.

**Comment by KendallDoesCoding** [comment]
Hey willnode,

Thanks for fiixing the issue!
